version: '3.1'

services:

  core-data:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        buildno: 'docker'

    volumes:
      - .:/apps
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
          - NODE_ENV=docker

  mongo:
    image: mongo
#    command: bash -c "mongorestore /backup"
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
     - ./backup-mongo:/backup


  redis:
    image: redis
    restart: unless-stopped